services:
  redis:
    image: redis:8.10.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:18.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jrust.pgrs
      POSTGRES_DB: SfxLibrary
    volumes:
      - postgres_data:/var/lib/postgresql/

  api:
    build:
      context: ./SoundEffectLibrary.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=SfxLibrary;Username=postgres;Password=Jrust.pgrs"
      ConnectionStrings__Redis: "redis:6379"
      AudioStorage__RootPath: "/app/audio"
    volumes:
    - "E:/SoundEffectLibrary:/app/audio"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: